### PR TITLE
Update/nightly 2021 10 29

### PR DESCRIPTION
**Pull request by antoyo**

### CODE REVIEW

**Comment by bjorn3** [comment]
I think you messed up the git subtree command. It seems like you are now pulling in the whole rust repo.

**Comment by bjorn3** [comment]
Try these commands: https://github.com/bjorn3/rustc_codegen_cranelift/blob/master/scripts/rustup.sh#L45-L52

**Comment by antoyo** [comment]
That looks similar to what I did.
I'm trying again and now git exists with an error code of 1 without any error message.
Now sure what I'm doing wrong.

**Comment by bjorn3** [comment]
What is the exact command you used?

**Comment by antoyo** [comment]
```
git subtree push -P compiler/rustc_codegen_gcc/ ../rustc_codegen_gccjit/ sync_from_rust
```
Now I'm stracing `git` to understand why it exits with -1 and seeing stuff like:
```
faccessat2(AT_FDCWD, "/Projects/rust/.git/subtree-cache/36643/9775ffef2a4c3a36cadb58b72ea60cefb92c86ae\n5526d902508178293b98b4d8b7b39802107dc395", R_OK, AT_EACCESS) = -1 ENOENT (No such file or directory)
```
which does not seem ok.

**Comment by bjorn3** [comment]
You could try deleting `.git/subtree-cache`. It works fine for me:

```
$ git subtree push -P compiler/rustc_codegen_gcc/ ../rustc_codegen_gcc/ sync_from_rust
git push using:  ../rustc_codegen_gcc/ sync_from_rust
Enumerating objects: 274, done.
Counting objects: 100% (274/274), done.
Delta compression using up to 4 threads
Compressing objects: 100% (148/148), done.
Writing objects: 100% (274/274), 194.18 KiB | 10.22 MiB/s, done.
Total 274 (delta 138), reused 211 (delta 114), pack-reused 0
remote: Resolving deltas: 100% (138/138), done.
To ../rustc_codegen_gcc/
 * [new branch]              d5a6aafb8847eeae39f23f852dd33e32ca2ca914 -> sync_from_rust
```

I pushed it to https://github.com/bjorn3/rustc_codegen_gcc/tree/sync_from_rust if you want to use that instead.

**Comment by antoyo** [comment]
I'd like to understand how to do it right for the future ;) .

I was able to reproduce the same as this PR (i.e. with all the useless commits), so I'm not sure what I'm doing wrong.
Do you execute the following:
```bash
#!/bin/bash

git clone https://github.com/rust-lang/rust
git clone https://github.com/rust-lang/rustc_codegen_gcc

cd rust
git subtree push -P compiler/rustc_codegen_gcc/ ../rustc_codegen_gcc/ sync_from_rust
```
?

**Comment by bjorn3** [comment]
Yeah, pretty much. Which git version do you have? I used a self-built version of https://github.com/gitgitgadget/git/pull/493 (commit gitgitgadget/git@19db9cfb68c762a262f3f3b6a0781cdc6bf49bfe). I think you are hitting

> A mainline commit that does not contain the subtree folder could be erroneously identified as a subtree commit, which would add the entire mainline history to the subtree.

which that PR fixes.

**Comment by antoyo** [comment]
That was it!
Thanks!

**Pull request closed without merging**
