### PR TITLE
Rename `y.sh test --clean-ui-tests` to `y.sh clean ui-tests`

### LINKED ISSUE #404: Rename `y.sh test --clean-ui-tests` to `y.sh clean ui-tests`

### PR DESCRIPTION
**Pull request by rowan-sl**
Fixes #404

### CODE REVIEW

**Comment by antoyo** [comment]
It seems like the Intel Software Development Emulator download link no longer works.
Could you please update [these lines](https://github.com/rust-lang/rustc_codegen_gcc/blob/master/.github/workflows/stdarch.yml#L44-L46) to the following:
```
dir=sde-external-9.33.0-2024-01-07-lin
file=$dir.tar.xz
wget https://downloadmirror.intel.com/813591/$file
```
This should fix the issue.
Thanks!

**Comment by rowan-sl** [comment]
Updated SDE, that part of the CI test appears to work now

**Comment by rowan-sl** [comment]
nevermind, some tests are failing to download crates from crates.io

**Comment by antoyo** [comment]
Seems like download failures. I restarted the CI.

**Comment by antoyo** [comment]
Thanks for your contribution!

**Pull request merged**
