### PR TITLE
Remove unused dependency on object

### PR DESCRIPTION
**Pull request by bjorn3**

### CODE REVIEW

**Comment by antoyo** [comment]
Sorry for not looking at this earlier.
I wanted to check what was using this crate before.
I couldn't find it, so do you happen to know what was using this crate?

**Comment by bjorn3** [comment]
Did you maybe copy it from cg_clif? Cg_clif uses it for creating the metadata object and used to use it for reading metadata from dylibs (now moved into cg_ssa).

**Comment by antoyo** [comment]
You mean the archive code that was removed in this [PR](https://github.com/rust-lang/rustc_codegen_gcc/pull/79/files)?

**Comment by bjorn3** [comment]
No, the metadata loader and dylib metadata writing.

**Comment by antoyo** [comment]
Oh well. I guess it's not that important to find anyway.
Thanks!

**Pull request merged**
